"""Disease reference library used by farmer advisory and student study cards."""
from __future__ import annotations

DISEASE_LIBRARY: dict[str, dict[str, str]] = {
    "Blast": {"agent": "Fungus", "hosts": "Rice, ragi", "symptom": "Spindle-shaped spots on leaves; neck blast can reduce grain filling.", "favour": "High humidity, cloudy weather, excess nitrogen and susceptible variety.", "cycle": "Spore survival → infection → lesion → new spores → spread by wind/rain splash.", "study": "Important example for disease triangle and epidemiology.", "management": "Use resistant varieties, balanced nitrogen, clean seed and local recommended fungicide only when needed."},
    "Bacterial Leaf Blight": {"agent": "Bacterium", "hosts": "Rice", "symptom": "Yellowing from leaf tip/margins, wavy lesion edge.", "favour": "Rain, wind injury, flooding and susceptible varieties.", "cycle": "Bacteria survive in residue/seed → enter wounds → spread by rain/water.", "study": "Good example for bacterial disease and sanitation.", "management": "Use resistant varieties, avoid clipping seedlings, balanced nutrition and field sanitation."},
    "Sheath Blight": {"agent": "Fungus", "hosts": "Rice", "symptom": "Oval lesions on sheath near water line.", "favour": "Dense crop, high nitrogen, high humidity.", "cycle": "Sclerotia survive in soil → infect sheath → spread plant to plant.", "study": "Shows role of canopy microclimate.", "management": "Wider spacing, balanced fertilizer, drainage and local advisory-based control."},
    "Late Blight": {"agent": "Oomycete", "hosts": "Potato, tomato", "symptom": "Water-soaked lesions, brown patches and rapid spread in cool humid weather.", "favour": "Cool cloudy humid weather and leaf wetness.", "cycle": "Sporangia spread by wind/rain → infect leaves/tubers → epidemic cycle.", "study": "Classic disease for epidemic explanation.", "management": "Avoid wet foliage, remove infected plants, use healthy seed and follow warning-based protection."},
    "Early Blight": {"agent": "Fungus", "hosts": "Tomato, potato", "symptom": "Target-board concentric rings on older leaves.", "favour": "Warm humid weather and weak plants.", "cycle": "Survives in debris → spores infect leaves → repeated spread.", "study": "Useful for distinguishing old-leaf diseases.", "management": "Crop rotation, remove debris, balanced nutrition and avoid overhead irrigation."},
    "Powdery Mildew": {"agent": "Fungus", "hosts": "Cucurbits, mango, pulses", "symptom": "White powdery growth on leaves, flowers or fruits.", "favour": "Warm dry days with humid nights.", "cycle": "Spores spread by wind and infect tender tissues.", "study": "Good for symptoms-based diagnosis.", "management": "Use resistant varieties, spacing, remove infected parts and local need-based protection."},
    "Downy Mildew": {"agent": "Oomycete-like pathogen", "hosts": "Cucurbits, cole crops, onion", "symptom": "Yellow angular spots above and downy growth below leaves.", "favour": "Cool humid weather and leaf wetness.", "cycle": "Spores form on leaf underside and spread in moist conditions.", "study": "Useful for comparing with powdery mildew.", "management": "Improve aeration, avoid wet leaves and follow local advisory."},
    "Leaf Curl": {"agent": "Virus complex", "hosts": "Tomato, chilli, cotton, papaya", "symptom": "Leaf curling, stunting, yellowing and poor flowering.", "favour": "Whitefly/thrips vector pressure and infected seedlings.", "cycle": "Virus survives in host plants → vector acquisition → transmission to healthy crop.", "study": "Important vector-borne disease example.", "management": "Use healthy seedlings, vector management, remove infected plants early and weed control."},
    "Wilt": {"agent": "Fungal/bacterial/nematode complex", "hosts": "Brinjal, tomato, pulses, banana", "symptom": "Drooping leaves, vascular browning and plant death.", "favour": "Soil-borne inoculum, poor drainage, susceptible varieties.", "cycle": "Survives in soil → root infection → vascular blockage.", "study": "Useful for soil-borne disease diagnosis.", "management": "Crop rotation, resistant varieties, drainage, soil solarization/bio-control where suitable."},
    "Anthracnose": {"agent": "Fungus", "hosts": "Mango, chilli, papaya", "symptom": "Dark sunken lesions on leaves/fruits and fruit rot.", "favour": "High humidity and rain splash.", "cycle": "Survives in infected debris → spores spread by rain splash.", "study": "Important post-harvest and field disease.", "management": "Sanitation, pruning, avoid fruit injury and use local recommendation."},
    "Rust": {"agent": "Fungus", "hosts": "Wheat, groundnut, beans", "symptom": "Rust-coloured pustules on leaves/stems.", "favour": "Humidity and susceptible varieties.", "cycle": "Air-borne spores infect crop repeatedly.", "study": "Classic disease for spore dispersal.", "management": "Resistant varieties, monitoring and timely local advisory."},
    "Black Rot": {"agent": "Bacterium", "hosts": "Cabbage, cauliflower", "symptom": "V-shaped yellow lesions from leaf margin with black veins.", "favour": "Warm wet conditions and infected seed.", "cycle": "Seed/debris survival → splash/wound entry → systemic spread.", "study": "Important vegetable bacterial disease.", "management": "Use clean seed, crop rotation, avoid overhead irrigation and sanitation."},
}

__all__ = ["DISEASE_LIBRARY"]
