"""Pest reference library used by farmer advisory and student study cards."""
from __future__ import annotations

PEST_LIBRARY: dict[str, dict[str, str]] = {
    "Brown Plant Hopper": {"type": "Sucking pest", "hosts": "Rice", "id": "Brown insects at plant base; hopper burn patches.", "damage": "Sucks sap and causes yellowing, drying and hopper burn.", "life": "Egg → nymph → adult; population rises in humid, dense, nitrogen-rich fields.", "study": "Important example for ETL, resistant varieties and IPM in rice.", "management": "Avoid excess nitrogen, maintain spacing, conserve predators, drain water briefly and use need-based insecticide only after ETL."},
    "Stem Borer": {"type": "Borer", "hosts": "Rice, maize, sugarcane", "id": "Dead heart at vegetative stage and white ear at reproductive stage.", "damage": "Larva bores into stem and cuts central shoot or panicle supply.", "life": "Egg mass → larva inside stem → pupa → moth.", "study": "Classic pest for lifecycle diagram and symptom-based diagnosis.", "management": "Use pheromone traps, remove stubbles, balanced fertilizer and need-based control."},
    "Fall Armyworm": {"type": "Defoliator", "hosts": "Maize", "id": "Windowing on leaves, sawdust-like frass in whorl.", "damage": "Larvae feed inside whorl and reduce leaf area.", "life": "Egg mass → larval instars → pupa → moth; rapid multiplication possible.", "study": "Important invasive pest for surveillance and IPM.", "management": "Early whorl scouting, pheromone traps, conserve natural enemies and follow local advisory."},
    "Aphids": {"type": "Sucking pest", "hosts": "Mustard, vegetables, pulses, potato", "id": "Soft green/black colonies on tender parts.", "damage": "Sap sucking, honeydew, sooty mould and virus transmission.", "life": "Fast multiplication; many generations in cool weather.", "study": "Useful for explaining vector transmission.", "management": "Monitor tender shoots, use yellow sticky traps, conserve ladybird beetles and avoid unnecessary sprays."},
    "Whitefly": {"type": "Sucking/vector pest", "hosts": "Cotton, tomato, okra, chilli", "id": "Tiny white adults fly when leaves are disturbed.", "damage": "Sap sucking, honeydew and viral disease spread.", "life": "Egg → nymph → adult on leaf underside.", "study": "Key pest for viral disease relationship.", "management": "Yellow traps, weed removal, resistant varieties and need-based management."},
    "Thrips": {"type": "Rasping-sucking pest", "hosts": "Chilli, onion, cotton", "id": "Silvery streaks, curling leaves, tiny slender insects.", "damage": "Leaf curling, flower damage and virus transmission.", "life": "Egg inserted in tissue; nymphs feed on leaves/flowers.", "study": "Important in chilli leaf curl complex.", "management": "Blue sticky traps, irrigation to reduce dry stress, remove weeds and need-based control."},
    "Jassid": {"type": "Sucking pest", "hosts": "Okra, cotton, brinjal", "id": "Leaf yellowing and curling from margins.", "damage": "Toxic saliva causes hopper burn-like leaf margin injury.", "life": "Egg → nymph → adult on underside of leaves.", "study": "Good example for pest injury symptoms.", "management": "Use tolerant varieties, balanced nitrogen and regular underside leaf scouting."},
    "Fruit Borer": {"type": "Borer", "hosts": "Tomato, brinjal, chilli, pulses", "id": "Circular holes, frass and larva inside fruit/pod.", "damage": "Direct market loss due to damaged fruits and pods.", "life": "Egg → larva bores fruit → pupa → moth.", "study": "Important for economic injury and pheromone traps.", "management": "Pheromone traps, remove damaged fruits, bird perches and need-based control."},
    "Fruit Fly": {"type": "Fruit pest", "hosts": "Cucurbits, mango, guava", "id": "Puncture marks, rotting fruit and maggots inside.", "damage": "Fruit drop and unmarketable produce.", "life": "Egg inside fruit → maggot → soil pupa → adult fly.", "study": "Good lifecycle diagram pest.", "management": "Field sanitation, bait traps, fruit bagging and collection/destruction of infested fruits."},
    "Diamondback Moth": {"type": "Leaf feeder", "hosts": "Cabbage, cauliflower", "id": "Small green larvae scrape leaves; windowing damage.", "damage": "Reduces curd/head quality in cole crops.", "life": "Egg → larva → pupa → moth; many generations.", "study": "Known for insecticide resistance.", "management": "Use netting, biological control, crop rotation and rotate control methods."},
    "Mites": {"type": "Arachnid pest", "hosts": "Chilli, vegetables", "id": "Tiny mites, bronzing, curling and rough leaf surface.", "damage": "Reduces photosynthesis and causes deformity.", "life": "Egg → larva/nymph → adult; dry weather favours increase.", "study": "Useful to explain pest-weather relationship.", "management": "Avoid dusty stress, maintain irrigation and use recommended acaricide only when needed."},
    "Mealybug": {"type": "Sucking pest", "hosts": "Papaya, cotton, fruits", "id": "White cottony masses on stem, leaves and fruits.", "damage": "Sap loss, sooty mould and weak growth.", "life": "Eggs in cottony sac; crawlers spread to new parts.", "study": "Good for biological control examples.", "management": "Remove infested parts, manage ants and conserve parasitoids/predators."},
}

__all__ = ["PEST_LIBRARY"]
